# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development: &development
  adapter: postgresql
  encoding: unicode
  database: spree_demo_db
  pool: 5
  username: postgres
  password: postgres
  host: localhost
